version: '3.9'

services:
  database:
    container_name: dummy-ecommerce-db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}



#start docker: docker compose up -d <servicerName>
#check-up db: docker exec -it <containerName> psql -U postgres
#\dt -> table list
#TODO: aaaaaa